menu:
  # 文章:
  #   隧道: /archives/ || anzhiyu-icon-box-archive
  #   分类: /categories/ || anzhiyu-icon-shapes
  #   标签: /tags/ || anzhiyu-icon-tags

  # 友链:
  #   友人帐: /link/ || anzhiyu-icon-link
  #   朋友圈: /fcircle/ || anzhiyu-icon-artstation
  #   留言板: /comments/ || anzhiyu-icon-envelope

  # 我的:
  #   音乐馆: /music/ || anzhiyu-icon-music
  #   追番页: /bangumis/ || anzhiyu-icon-bilibili
  #   相册集: /album/ || anzhiyu-icon-images
  #   小空调: /air-conditioner/ || anzhiyu-icon-fan

  # 关于:
  #   关于本人: /about/ || anzhiyu-icon-paper-plane
  #   闲言碎语: /essay/ || anzhiyu-icon-lightbulb
  #   随便逛逛: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1

# nav相关配置
nav:
  enable: false
  travelling: false
  clock: false
  menu:
    - title: 网页
      item:
        - name: 博客
          link: https://hexo.anheyu.com/
          icon: /img/favicon.ico
    - title: 项目
      item:
        - name: 安知鱼图床
          link: https://image.anheyu.com/
          icon: https://image.anheyu.com/favicon.ico

# mourn （哀悼日，指定日期网站简单变灰，不包括滚动条）
# 注意： 仅网站首页变灰，其他页面正常显示
mourn:
  enable: false
  days: [4-5, 5-12, 7-7, 9-18, 12-13]

# Code Blocks (代码相关)
# --------------------------------------

highlight_theme: light #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 330 # unit: px
code_word_wrap: false

# copy settings
# copyright: Add the copyright information after copied content (複制的内容后面加上版权信息)
# copy: enable 复制后弹窗提示版权信息
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# social settings (社交图标设置)
# formal:
#   name: link || icon
social:
  # Github: https://github.com/anzhiyu-c || anzhiyu-icon-github
  # BiliBili: https://space.bilibili.com/372204786 || anzhiyu-icon-bilibili

# 作者卡片 状态
author_status:
  enable: false
  # 可以是任何图片，建议放表情包或者emoji图片，效果都很好，[表情包速查](https://emotion.xiaokang.me/)
  statusImg: "https://bu.dusays.com/2023/08/24/64e6ce9c507bb.png"
  skills:
    # - 🤖️ 数码科技爱好者
    # - 🔍 分享与热心帮助
    # - 🏠 智能家居小能手
    # - 🔨 设计开发一条龙
    # - 🤝 专修交互与设计
    # - 🏃 脚踏实地行动派
    # - 🧱 团队小组发动机
    # - 💢 壮汉人狠话不多

# search (搜索)
# --------------------------------------

# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6
  tags:
    # - 前端
    # - Hexo

# Docsearch
# Apply and Option Docs: see https://docsearch.algolia.com/
# Crawler Admin Console: see https://crawler.algolia.com/
# Settings: https://www.algolia.com/
docsearch:
  enable: false
  appId: # see email
  apiKey: # see email
  indexName: # see email
  option:

# Local search
local_search:
  enable: false
  preload: true
  CDN:

# Math (数学)
# --------------------------------------
# About the per_page
# if you set it to true, it will load mathjax/katex script in each page (true 表示每一页都加载js)
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' in page's front-matter)
# (false 需要时加载，须在使用的 Markdown Front-matter 加上 mathjax: true)

# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# Image (图片设置)
# --------------------------------------

# Favicon（网站图标）
favicon: /favicon.ico

# Avatar (头像)
avatar:
  img: https://bu.dusays.com/2023/04/27/64496e511b09c.jpg
  effect: false

# Disable all banner image
disable_top_img: false

# The banner image of home page
index_img: false # "background: url() top / cover no-repeat"

# If the banner of page not setting, it will show the top_img
default_top_img: false

cover:
  # display the cover or not (是否显示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面显示的位置)
  # left/right/both
  position: left
  # When cover is not set, the default cover is displayed (当没有设置cover时，默认的封面显示)
  default_cover:
    # - /img/default_cover.jpg

# Replace Broken Images (替换无法显示的图片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page
error_404:
  enable: true
  subtitle: "请尝试站内搜索寻找文章"
  background: https://bu.dusays.com/2023/05/08/645907596997d.gif

post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: simple # date/relative/simple 显示日期还是相对日期 或者 简单日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标籤
    label: false # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: date # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标籤
    label: true # true or false 显示描述性文字
    unread: false # true or false 文章未读功能

# 主色调相关配置
mainTone:
  enable: false # true or false 文章是否启用获取图片主色调
  mode: api # colorthief/cdn/api/both colorthief模式为前端获取图片主色调，cdn模式为图片url+im